TUK-DP/backend

diary/textrank.py

[refactor] textRank 리팩토링

---

.dockerignore
.github/workflows/deploy.yml
Dockerfile

- dockerfile 생성
- deploy workflow 생성

[chore] deploy workflow 생성

---

diary/textrank.py

[feat] han_spell 제거 및 불용어 처리 완료

---

diary/textrank.py

- sentence 의 vocab이 생각했던 로직과 달랐기 때문에 생겼던 오류였음 (내 실수)

[fix] 문장 그래프를 뽑지않음으로 에러 해결

---

diary/serializers.py
diary/views.py

- 일기 작성시 2번 저장되는 오류 수정
- 일기 수정시 2번 저장되는 오류 수정
- x

[fix] 연결된 함수 호출을 분리해서 에러 해결

---

.dockerignore
.github/workflows/deploy.yml
.github/workflows/hotfix.yml
Dockerfile
config/settings.py
diary/serializers.py
diary/textrank.py
diary/views.py
requirements.txt

- refactor19 브랜치에 develop commit들 가져오기
- X

[chore] develop commit들 가져오기

---

diary/textrank.py
diary/views.py

- 짧은 단어 작성시 일기 작성 안되는 오류 해결
- X

[fix] 짧은 단어 작성시 일기 작성 안되는 오류 해결

---

diary/serializers.py
diary/urls.py
diary/views.py

[feat] 유저 아이디와 날짜로 일기 조회 구현

---

.dockerignore
.gitignore
DjangoBaseImage/Dockerfile
Dockerfile
docker-compose-dev.yml
docker-compose-prod.yml
docker-compose.yml
wait-for-services.sh

- Dockerfile 정리
- docker-compose-prod 정의
- docker-compose-dev 정의
docker-compose-dev.yml 사용법
```bash
docker-compose -f docker-compose.yml -f docker-compose-dev.yml -p dp-dev up -d --build
```

[chore] Dockerfile 정리 및 배포 docker-compose-prod, dev yml 정의

---

diary/serializers.py
diary/views.py
users/serializers.py
users/views.py

- diary, user view 에 트랜젝션 설정
- 작업사항 2
- user view 약간의 리팩토링
- diary view 에서 memory가 None 일때 실행되는 코드 제거

[chore] diary, user view 에 트랜젝션 설정

---

.github/workflows/deploy.yml
.github/workflows/hotfix.yml

[chore] 배포 스크립트 수정

---

config/settings.py
config/urls.py
docker-compose-dev.yml
image/admin.py
image/apps.py
image/models.py
image/s3_modules/s3_handler.py
image/serializer.py
image/tests.py
image/urls.py
image/views.py
requirements.txt

[feat] s3 연동 (이미지 업로드 기능 구현)

---

diary/serializers.py
diary/urls.py
diary/views.py
docker-compose-dev.yml

- 일기 삭제 기능 구현
- `.env-django` 없이 docker-dev 가능하게 수정

[feat] 일기 삭제 기능 구현

---

users/serializers.py
users/urls.py
users/views.py

[feat] 닉네임 중복확인 구현

---

diary/graph.py
diary/serializers.py
diary/urls.py
diary/views.py
docker-compose-dev.yml

- 그래프 데이터 가져오는 API 구현
- 개발 docker-compose 파일 makemigrations 가능하게 수정

그래프 데이터 가져오는 API 구현

---

diary/serializers.py
diary/urls.py
diary/views.py

- 퀴즈 제공 API 구현
- 답안 채점 API 구현
- 변수명 camelCase로 통일화

[feat] 퀴즈 문제와 답안 API 분리

---

diary/serializers.py
diary/urls.py
diary/views.py

[feat] 키워드 조회 API 구현

---

config/settings.py

위 버튼을 누르면
위 처러럼 인증창이 나옴
특정 API 의 자물쇠를 누르면 인증정보가 입력 되어있는지 확인 가능함
인증정보를 기입후 API 호출시 요청정보 헤더에 값이 들어간다.

[chore] AccessToken 과 RefreshToken을 인증 받기 위한 Swagger Setting

---

diary/views.py

[fix] 키워드 이미지 검색 not null 필터링 추가

---

diary/serializers.py
diary/views.py

[fix] 키워드 답안 제출 공백 허용

---

users/serializers.py
users/validator.py
users/views.py

- user 수정 patch -> put 으로 변경
- user 수정 url : (patch) /user/{userId} -> (put) /user 로 변경

[refactor] user 수정 patch -> put 으로 변경

---

docker-compose-dev.yml
image/gpt/GenerateImage.py
requirements.txt

[feat] 번역기 API 변경

---

.github/workflows/deploy.yml
.github/workflows/hotfix.yml

[chore] deepl apikey cicd 설정

---

diary/serialziers/diary_response_serializers.py

- diary 키워드가 없는경우 diary 그림 띄울수 있게 diary imgUrl 추가

[refactor] diary 키워드가 없는경우 diary 그림 띄울수 있게 diary imgUrl 추가

---

.github/workflows/deploy.yml
.github/workflows/hotfix.yml
docker-compose-prod.yml

[fix] .env-deepl 추가

---

.gitignore
.gitmodules

- 환경변수를 관리하는 env 서브모듈추가
위 pr 이 develop 에 merge 된 이후 develop 브랜치에서 아래 명령어 실행
```jsx
git submodule init
git submodule update
```
아래와 같이 readme 파일이 잘 보이면 성공
```jsx
git submodule update --remote
```
```jsx
git submodule update --remote --merge
또는
git submodule update --remote --rebase
```

[chore] 환경변수를 관리하는 env 서브모듈추가

---

Dockerfile-celery
docker-compose-dev.yml
docker-compose-prod.yml
docker-compose.yml
image/serializers.py
image/urls.py
image/views.py
requirements.txt
tasks.py

- celery 연동하여 이미지 생성 작업하기
이미지 관련하여 호출할 api는 2개
POST image/generate는 기존에 우리가 사용했던 api와 동일합니다. 다만 달라진 내용은 이미지 url을 알려주지 않고 celery에게 작업을 맡긴 뒤 해당 taskId를 넘겨준다는 것 입니다. 
GET image/generate에서 taskId를 가지고 조회가 가능합니다. 이때 각 상태에 따라 다르게 값이 나오게 됩니다.
이렇게 변경을 하게 된 이유는 기존 api 한번 호출 시 오래 대기를 하는 경우가 있었는데, 이는 성능이나 사용감 측면에서 좋지 않기 때문입니다.
따라서 해당 요청을 비동기 처리 방식으로 변경하여 사용감 측면이나 성능적인 측면에서 효율을 높이기 위하여 변경하였습니다. 
<br>
- 변경된 API Docs
**POST image/generate**
request
```JSON
{
"password": "string",
"prompt": "string",
"n": 3
}
```
response
```json
{
"isSuccess": true,
"message": "OK",
"result": {
"taskId": "12345678-1234-1234-1234-123456789123"
}
}
```
**GET image/generate**
request
```
/image/generate?taskId=12345678-1234-1234-1234-123456789123
```
response 
PENDING일 때
```json
{
"isSuccess": true,
"message": "OK", …
```

[feat] celery 연동하여 이미지 생성

---

diary/views/diary_query_views.py

- 일기에 이미지가 존재하는지 여부 추가
endpoint => diary/check
HTTP Method => GET
Request
```
/diary/check?userId=1&year=2024&month=8'
```
Response
```JSON
{
"isSuccess": true,
"message": "OK",
"result": {
"2024-8": {
...
,
"8": {
"isExist": false,
"diaryId": null,
"imgExist": false
},
"9": {
"isExist": true,
"diaryId": 10,
"imgExist": true
},
"10": {
"isExist": true,
"diaryId": 9,
"imgExist": true
},
"11": {
"isExist": false,
"diaryId": null,
"imgExist": false
},
...
}
}
}
```
- X

fix/175 일기 이미지 여부 추가
